### ISSUE TITLE
Touch / Apple Pencil Support

### ISSUE THREAD

**Issue by kitsunekage7** [gergoszaszvaradi/greyboard#5] opened 2021-03-18 22:40 UTC
Hi, 
Came across your app, the first collaborative whiteboard that I've come across that actually looks good and provides a great user experience. 

I've no idea what your roadmap is for the Greyboard, but trying it out on my iPad I've noticed that it does not recognise touch input, either from normal touch events or the apple Pencil (Stylus).

I was wondering if this is on purpose, or just functionality that has not been implemented yet. 

Doing a little digging, it looks like you capture the touch events as per - https://w3c.github.io/touch-events/#dom-touch-touchtype 

But still, great app!

**Comment by gergoszaszvaradi** [comment] 2021-03-24 09:54
@kitsunekage7 I added touch support, but sadly I don't have access to an Apple Pencil and an iPad, so I can't confirm that it fully supports it.
I'll not close this issue until I know that it works as it should.

**Comment by kitsunekage7** [comment] 2021-03-25 23:29
@gergoszaszvaradi, touch support works a treat with Apple Pencil, and Scribble also works seamlessly when entering text. The only issue is that when you are touching the screen, it tries to scroll as you draw. I manage to replicate this in Chrome Dev tools by emulating an iPad Pro. 
After a quick google looks like this is a thing with iOS Safari. 
http://bencentra.com/code/2014/12/05/html5-canvas-touch-events.html#touch-input provides a quick explanation.
I added the following to core.ts and it solved the problem. 

`        // Prevent scrolling when touching the canvas
        this.graphics.canvas.addEventListener("touchstart", function (e) {
            if (e.target == canvas) {
            e.preventDefault();
            }
        }, false);
        this.graphics.canvas.addEventListener("touchend", function (e) {
            if (e.target == canvas) {
            e.preventDefault();
            }
        }, false);
        this.graphics.canvas.addEventListener("touchmove", function (e) {
            if (e.target == canvas) {
            e.preventDefault();
            }
        }, false);
`
Created a Pull request, let me know what you think.

**Comment by gergoszaszvaradi** [comment] 2021-03-26 06:20
@kitsunekage7 Since you confirmed that touch support worked with only minor problems that have been fixed already, I'm going to close this issue.

**Closed as completed by gergoszaszvaradi** 2021-03-26 06:20 UTC
Labels: enhancement
